name: sarthakgupta_api_integration
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0
flutter_launcher_name:
  name: "SarthakGupta_api_integration"
environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
